# 开发环境的配置文件
# 应用服务WEB访问端口
server:
  port: 8080
# debug
debug: true
# 配置Spring
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog
    password: 123456
    url: jdbc:mysql://lostred.info:3306/blog?useUnicode=true&characterEncoding=utf8

# 配置MyBatis-Plus
mybatis-plus:
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不用注解实体字段)
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
  # 别名
  type-aliases-package: info.lostred.blog.entity,info.lostred.blog.vo

# 文件上传
file:
  # 静态资源访问虚拟路径
  staticAccessPath: /upload/**
  # 文件上传目录
  uploadFolder: C:/upload/
  # 文件主机
  host: http://localhost:8080